import Head from "next/head";
import Indicator from "../components/Indicator";
import Loading from "../components/Loading";
import useSWR, { Fetcher } from "swr";
import { IndicatorsModel } from "../interfaces/IndicatorsModel";

const fetcher: Fetcher<IndicatorsModel, string> = (...args) =>
  fetch(...args).then((res) => res.json());

const Home: React.FC = () => {
  const { data, error } = useSWR<IndicatorsModel>(
    process.env.NEXT_PUBLIC_API_ENDPOINT,
    fetcher
  );

  if (error) return <div>Failed to load</div>;
  if (!data) return <Loading />;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Indicator data={data.bitcoin} />
        <Indicator data={data.dolar_intercambio} />
        <Indicator data={data.dolar} />
        <Indicator data={data.euro} />
        <Indicator data={data.imacec} />
        <Indicator data={data.ipc} />
        <Indicator data={data.ivp} />
        <Indicator data={data.libra_cobre} />
        <Indicator data={data.tasa_desempleo} />
        <Indicator data={data.tpm} />
        <Indicator data={data.uf} />
        <Indicator data={data.utm} />
      </main>
    </div>
  );
};

export default Home;
